


with hashes as (
  SELECT 
    *,
    hash(Tenant_SK, PropertyAddress) as hash_PropertyAddress,
    hash(Tenant_SK, Room) as hash_Room,
    hash(Tenant_SK, FirstName) as hash_FirstName,
    hash(Tenant_SK, MiddleName) as hash_MiddleName,
    hash(Tenant_SK, LastName) as hash_LastName,
    hash(Tenant_SK, DateOfBirth) as hash_DateOfBirth,
    hash(Tenant_SK, NINumber) as hash_NINumber,
    hash(Tenant_SK, CheckinDate) as hash_CheckinDate,
    hash(Tenant_SK, CheckoutDate) as hash_CheckoutDate,
    hash(Tenant_SK, NewHBClaim) as hash_NewHBClaim,
    hash(Tenant_SK, HBClaimRefNumber) as hash_HBClaimRefNumber,
    hash(Tenant_SK, ReferralAgency) as hash_ReferralAgency,
    hash(Tenant_SK, GroupedReferralAgency) as hash_GroupedReferralAgency,
    hash(Tenant_SK, Age) as hash_Age,
    hash(Tenant_SK, Gender) as hash_Gender,
    hash(Tenant_SK, Religion) as hash_Religion,
    hash(Tenant_SK, Ethnicity) as hash_Ethnicity,
    hash(Tenant_SK, Nationality) as hash_Nationality,
    hash(Tenant_SK, Disability) as hash_Disability,
    hash(Tenant_SK, SexualOrientation) as hash_SexualOrientation,
    hash(Tenant_SK, SpokenLanguage) as hash_SpokenLanguage,
    hash(Tenant_SK, RiskAssessment) as hash_RiskAssessment,
    hash(Tenant_SK, LengthOfStay) as hash_LengthOfStay,
    hash(Tenant_SK, ProviderName) as hash_ProviderName,

    -- LAG to get previous values for comparison
    LAG(hash(Tenant_SK, PropertyAddress)) OVER w AS prev_hash_PropertyAddress,
    LAG(hash(Tenant_SK, Room)) OVER w AS prev_hash_Room,
    LAG(hash(Tenant_SK, FirstName)) OVER w AS prev_hash_FirstName,
    LAG(hash(Tenant_SK, MiddleName)) OVER w AS prev_hash_MiddleName,
    LAG(hash(Tenant_SK, LastName)) OVER w AS prev_hash_LastName,
    LAG(hash(Tenant_SK, DateOfBirth)) OVER w AS prev_hash_DateOfBirth,
    LAG(hash(Tenant_SK, NINumber)) OVER w AS prev_hash_NINumber,
    LAG(hash(Tenant_SK, CheckinDate)) OVER w AS prev_hash_CheckinDate,
    LAG(hash(Tenant_SK, CheckoutDate)) OVER w AS prev_hash_CheckoutDate,
    LAG(hash(Tenant_SK, NewHBClaim)) OVER w AS prev_hash_NewHBClaim,
    LAG(hash(Tenant_SK, HBClaimRefNumber)) OVER w AS prev_hash_HBClaimRefNumber,
    LAG(hash(Tenant_SK, ReferralAgency)) OVER w AS prev_hash_ReferralAgency,
    LAG(hash(Tenant_SK, GroupedReferralAgency)) OVER w AS prev_hash_GroupedReferralAgency,
    LAG(hash(Tenant_SK, Age)) OVER w AS prev_hash_Age,
    LAG(hash(Tenant_SK, Gender)) OVER w AS prev_hash_Gender,
    LAG(hash(Tenant_SK, Religion)) OVER w AS prev_hash_Religion,
    LAG(hash(Tenant_SK, Ethnicity)) OVER w AS prev_hash_Ethnicity,
    LAG(hash(Tenant_SK, Nationality)) OVER w AS prev_hash_Nationality,
    LAG(hash(Tenant_SK, Disability)) OVER w AS prev_hash_Disability,
    LAG(hash(Tenant_SK, SexualOrientation)) OVER w AS prev_hash_SexualOrientation,
    LAG(hash(Tenant_SK, SpokenLanguage)) OVER w AS prev_hash_SpokenLanguage,
    LAG(hash(Tenant_SK, RiskAssessment)) OVER w AS prev_hash_RiskAssessment,
    LAG(hash(Tenant_SK, LengthOfStay)) OVER w AS prev_hash_LengthOfStay
  FROM "asha_dev"."main_staging"."stg_tenant_data"
  WINDOW w AS (PARTITION BY Tenant_SK ORDER BY CycleNumberValue DESC)
)

SELECT
  *,
  CASE WHEN hash_PropertyAddress != prev_hash_PropertyAddress THEN 1 ELSE 0 END AS IsDifferent_PropertyAddress,
  CASE WHEN hash_Room != prev_hash_Room THEN 1 ELSE 0 END AS IsDifferent_Room,
  CASE WHEN hash_FirstName != prev_hash_FirstName THEN 1 ELSE 0 END AS IsDifferent_FirstName,
  CASE WHEN hash_MiddleName != prev_hash_MiddleName THEN 1 ELSE 0 END AS IsDifferent_MiddleName,
  CASE WHEN hash_LastName != prev_hash_LastName THEN 1 ELSE 0 END AS IsDifferent_LastName,
  CASE WHEN hash_DateOfBirth != prev_hash_DateOfBirth THEN 1 ELSE 0 END AS IsDifferent_DateOfBirth,
  CASE WHEN hash_NINumber != prev_hash_NINumber THEN 1 ELSE 0 END AS IsDifferent_NINumber,
  CASE WHEN hash_CheckinDate != prev_hash_CheckinDate THEN 1 ELSE 0 END AS IsDifferent_CheckinDate,
  CASE WHEN hash_CheckoutDate != prev_hash_CheckoutDate THEN 1 ELSE 0 END AS IsDifferent_CheckoutDate,
  CASE WHEN hash_NewHBClaim != prev_hash_NewHBClaim THEN 1 ELSE 0 END AS IsDifferent_NewHBClaim,
  CASE WHEN hash_HBClaimRefNumber != prev_hash_HBClaimRefNumber THEN 1 ELSE 0 END AS IsDifferent_HBClaimRefNumber,
  CASE WHEN hash_ReferralAgency != prev_hash_ReferralAgency THEN 1 ELSE 0 END AS IsDifferent_ReferralAgency,
  CASE WHEN hash_GroupedReferralAgency != prev_hash_GroupedReferralAgency THEN 1 ELSE 0 END AS IsDifferent_GroupedReferralAgency,
  CASE WHEN hash_Age != prev_hash_Age THEN 1 ELSE 0 END AS IsDifferent_Age,
  CASE WHEN hash_Gender != prev_hash_Gender THEN 1 ELSE 0 END AS IsDifferent_Gender,
  CASE WHEN hash_Religion != prev_hash_Religion THEN 1 ELSE 0 END AS IsDifferent_Religion,
  CASE WHEN hash_Ethnicity != prev_hash_Ethnicity THEN 1 ELSE 0 END AS IsDifferent_Ethnicity,
  CASE WHEN hash_Nationality != prev_hash_Nationality THEN 1 ELSE 0 END AS IsDifferent_Nationality,
  CASE WHEN hash_Disability != prev_hash_Disability THEN 1 ELSE 0 END AS IsDifferent_Disability,
  CASE WHEN hash_SexualOrientation != prev_hash_SexualOrientation THEN 1 ELSE 0 END AS IsDifferent_SexualOrientation,
  CASE WHEN hash_SpokenLanguage != prev_hash_SpokenLanguage THEN 1 ELSE 0 END AS IsDifferent_SpokenLanguage,
  CASE WHEN hash_RiskAssessment != prev_hash_RiskAssessment THEN 1 ELSE 0 END AS IsDifferent_RiskAssessment,
  CASE WHEN hash_LengthOfStay != prev_hash_LengthOfStay THEN 1 ELSE 0 END AS IsDifferent_LengthOfStay
FROM hashes